export const workspaceReviewBase = "/workspace/review";
export const workspaceFilesBase = "/workspace/files";
export const filesPreviewBase = "/files/preview/";

/** URL that serves a local file through the preview route. */
export function filePreviewUrl(path: string): string {
	return (
		filesPreviewBase +
		path.replaceAll("\\", "/").split("/").map(encodeURIComponent).join("/")
	);
}

export const endpoints = {
	root: "/",
	stream: "/stream",
	displayRefresh: "/display-refresh",
	codeTheme: "/code-theme",
	fonts: "/fonts",
	keybindHints: "/keybind-hints",
	minimalMode: "/minimal-mode",
	toolOutput: "/tool-output",
	toolbar: "/toolbar",
	sessionPerformanceClient: "/session-performance/client",
	sessionSidebar: "/session-sidebar",
	prompt: "/prompt",
	promptFollowUp: "/prompt/follow-up",
	promptDequeue: "/prompt/dequeue",
	promptQueueRemove: "/prompt/queue/remove",
	abort: "/abort",
	messagesOlder: "/messages/older",
	messagesTrim: "/messages/trim",
	sessionsNew: "/sessions/new",
	sessionsNewTemporary: "/sessions/new-temporary",
	sessionsSearch: "/sessions/search",
	sessionsMore: "/sessions/more",
	sessionsFavicon: "/sessions/favicon",
	sessionsImage: "/sessions/image",
	sessionsBackgroundAbort: "/sessions/background/abort",
	sessionsDelete: "/sessions/delete",
	sessionsRename: "/sessions/rename",
	sessionsResume: "/sessions/resume",
	sessionsForkToWorkspace: "/sessions/fork-to-workspace",
	workspaceOpen: "/workspace/open",
	workspaceSearch: "/workspace/search",
	workspaceBrowse: "/workspace/browse",
	workspaceCreateFolder: "/workspace/create-folder",
	workspaceFiles: workspaceFilesBase,
	workspaceFileContent: `${workspaceFilesBase}/content`,
	workspaceFileEntry: `${workspaceFilesBase}/entry`,
	workspaceReviewDiff: "/workspace/review/diff",
	workspaceReviewCommit: "/workspace/review/commit",
	workspaceReviewDiscard: "/workspace/review/discard",
	workspaceReviewHistory: "/workspace/review/history",
	workspaceReviewPreferences: "/workspace/review/preferences",
	workspaceReviewSubmit: "/workspace/review/submit",
	model: "/model",
	modelCycle: "/model/cycle",
	modelsRefresh: "/models/refresh",
	modelsScopeToggle: "/models/scope/toggle",
	thinking: "/thinking",
	thinkingCycle: "/thinking/cycle",
	thinkingVisibilityToggle: "/thinking/visibility/toggle",
	authOpenLogin: "/auth/open-login",
	authOpenLogout: "/auth/open-logout",
	authLoginStart: "/auth/login/start",
	authInput: "/auth/input",
	authLogout: "/auth/logout",
	authClose: "/auth/close",
	llamaOpen: "/llama/open",
	llamaToggle: "/llama/toggle",
	llamaClose: "/llama/close",
	extensionUiResponse: "/extensions/ui/respond",
	extensionUiEditor: "/extensions/ui/editor",
	treeOpen: "/tree/open",
	treeNavigate: "/tree/navigate",
	filesSearch: "/files/search",
	filesImport: "/files/import",
	filesOpen: "/files/open",
	filesPreview: `${filesPreviewBase}*`,
	inspector: "/vendor/datastar-inspector.min.js",
} as const;
